# Generated by Django 4.1 on 2023-03-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='added_to_watchlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='auctions.auction'),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
