# Generated by Django 4.1 on 2023-03-03 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_added_to_watchlist_user_watchlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='added_to_watchlist',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='auctions.auction'),
        ),
    ]
