# Generated by Django 4.1 on 2023-03-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_auction_added_to_watchlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist_auction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
