# Generated by Django 4.1 on 2023-03-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_user_watchlist_auction_id_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
