# Generated by Django 4.1 on 2023-03-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auction_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='closed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
